### ISSUE TITLE
Table row controls disappear when interacting with the columns

### ISSUE THREAD

**Issue by benfeather** [supercool/Table-Maker#43]
### Describe the bug

If you interact with the columns in a table field, the controls on the rows disappear.

![CleanShot 2024-01-25 at 13 14 19@2x](https://github.com/verbb/tablemaker/assets/43571410/fa86f580-9b92-4b29-b844-e362382c332b)

### Steps to reproduce

1. Add columns and rows to a table field and save the entry.
2. Interact with the columns, e.g., reorder the columns, add a new column, change the column type, etc.

### Craft CMS version

4.7.0

### Plugin version

4.0.6

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-4 as 4.0.7"`.

**Comment by benfeather** [comment]
I'm still seeing this issue after updating:

https://github.com/verbb/tablemaker/assets/43571410/4cb02aed-121e-44ec-8734-3ef71264f6b6

**Comment by engram-design** [comment]
From your video, isn't that working correctly? Adding a new column adds the new column to the "Table Content" field, and as you type the heading, that shows up as "Ooops"? Unless I'm being blind?

**Comment by benfeather** [comment]
Sorry, should have been more specific. In the video, when I click the "add a column" button, the controls (the reorder and delete buttons) in the table content section disappear. It happens in the bottom right corner of the video. Hope that makes more sense!

**Comment by engram-design** [comment]
Oh. gotcha! I missed that indeed. Yep, I can see that happening now. Should be fixed properly now!

**Comment by engram-design** [comment]
Fixed in [4.0.8](https://github.com/verbb/tablemaker/releases/tag/4.0.8)
