### ISSUE TITLE
Date and Time field values getting wiped

### ISSUE THREAD

**Issue by LauraMontgomery** [supercool/Table-Maker#54]
### Describe the bug

When using the Date and Time fields in TableMaker, any previous values added get wiped if I make any changes to the Table Columns. Times I have spotted this include:

- Adding a new column
- Editing the name of a column heading
- Updating the values in a dropdown field

Related, but I suppose technically a different issue, is that date fields also load with NaN/NaN/NaN - which I understand as a developer, but might scare the normal end-user.

### Steps to reproduce

1.  Create a table with Date and Time columns
Note that the date column field is populated with NaN/NaN/NaN, although the field itself works perfectly fine.

![Image](https://github.com/user-attachments/assets/aabd85dc-af44-49a9-880f-82b7517cbdbb)

2. Populate table with some data, and save the entry

![Image](https://github.com/user-attachments/assets/1a765c5a-b697-40a6-bea5-a81fa08b64c2)

3. After the entry has saved, add a new column to the table
Note that the previously entered values for Date and Time have now been wiped, alongside Date showing NaN/NaN/NaN again

![Image](https://github.com/user-attachments/assets/002c1f06-f300-4573-9a13-512ee2f9c029)

### Craft CMS version

5.6.4

### Plugin version

5.0.4

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-5 as 5.0.4"`.

**Comment by LauraMontgomery** [comment]
Hey, thank you for this. I've given it a test and it does seem like the Time field input is sorted but I'm still getting the same issues on the Date field. I've clear caches just in case it was something like that causing my issues, but still behaving strangely unfortunately.

**Comment by engram-design** [comment]
Hmm, I can't seem to replicate that with the Date column. It's doing the exact same thing as before? As in, changing the columns (adding new ones or changing the text of existing ones) is clearing the value?

Quick video here - https://share.cleanshot.com/z4YBf3md

**Comment by LauraMontgomery** [comment]
How odd that we are getting different results. In order to try and work out what's going on differently with mine:

1. I've updated Craft to 5.6.9.1 - in case it was specifically a Craft bug

2. My composer was set to `"minimum-stability": "beta"`:

- I changed this to `"minimum-stability": "dev"`
- Downgraded the plugin to 5.0.4
- Re-ran `composer require verbb/tablemaker:"dev-craft-5 as 5.0.4"` to get back to this version

3. I have tried in both Firefox and Chrome, in case it was something browser specific

The only thing I can think of which I wasn't sure about from your screen recording, is that the issues are after saving the entry. In my recording below, it starts at the point of having some content in the table and then saving the entry. At this point, when I add or edit the column headings, that's when there is the issue. I couldn't tell from your recording if you'd done that or not.

My screen recording: https://drive.google.com/file/d/1jw6Jld8XbQiCDJLaeFmTXDU7my-MC0sR/view?usp=drive_link

**Comment by engram-design** [comment]
Ah, yes I may have cropped the video too much, but I did save the entry along the way (it takes a while to save!). Appreciate the video, but looks like I need to request access for it.

**Comment by LauraMontgomery** [comment]
Oops, sorry about that. Hopefully you have access to it now?

**Comment by engram-design** [comment]
Thanks! Just reviewing now, but looks like you're replicating what I'm doing. I've even tested using Matrix just in case. Will keep looking into it.

**Comment by LauraMontgomery** [comment]
Oh yes, sorry I completely forgot about the fact that it's in a matrix. Sorry about that. If there's anything I can do to help with debugging, please let me know. Thank you for your patience in trying to fix something that isn't broken for you - I completely understand how awkward it is.
